services:
  clientapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "60000:8080"
      - "60001:5001"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MinaretOps;User Id=sa;Password=Minaret@2021;Encrypt=False;TrustServerCertificate=True
      - JWT__Key=bff5d0ac0670db1c5453be06af14dbd7
      - EmailSetting__fromEmail=zminaretagency@gmail.com
      - EmailSetting__appPassword=kctmiqpsqeyccqhg
      - EmailSetting__port=587
      - EmailSetting__smtp=smtp.gmail.com
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Minaret@2021
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

volumes:
  sql_data: