services:
  clientapi:
    build:
      context: .
      dockerfile: Client API/Dockerfile
    ports:
      - "60000:5000"
      - "60001:5001"
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=MinaretOps;User Id=sa;Password=Minaret@2021;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Minaret@2021
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

volumes:
  sql_data: