services:
  clientapi:
    image: ${DOCKER_REGISTRY-}clientapi
    build:
      context: .
      dockerfile: ClientAPI/Dockerfile
    volumes:
      - /var/www/clientapi/wwwroot/uploads:/app/wwwroot/uploads